version: "{build}"

platform: x64

branches:
  only:
    - master

build_script:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/atom/ci/master/build-package.ps1"))

clone_depth: 10

skip_tags: true

environment:
  APM_TEST_PACKAGES: linter intentions linter-ui-default busy-signal
  ATOM_LINT_WITH_BUNDLED_NODE: true

  matrix:
    - ATOM_CHANNEL: stable

install:
  - ps: Install-Product node 4

test: off
deploy: off
